# Currently, running this action will result in the deployed Lambdas to complain about a 'error: Error: Cannot find module'. The fix is to run terraform apply locally.
name: "Terraform: Apply"

concurrency:
  group: deploy-test
  cancel-in-progress: false

on:
  workflow_dispatch:
      
permissions:
  id-token: write
  contents: read

jobs:
    call-workflow-passing-data:
      uses: TomBenjaminMorris/github-actions-lib/.github/workflows/terraform-deploy-on-pr-merge.yml@master
      with:
        aws-default-region: eu-west-2
        tf-aws-role: ${{ vars.TF_AWS_ROLE }}
        tf-version: "1.0.1"
      secrets: inherit